name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run fmt && git diff-index --quiet HEAD
